wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.8.13
    cli_version: 0.15.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694690415.939022
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.8.13
      5: 0.15.3
      8:
      - 3
      - 5
